name = "GregTech Odyssey"
version = "0.5.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2bbb9eb3aa613ee845661faac37382ea484cfe800243f5277506628a1459e41"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
