name = "GregTech Odyssey"
version = "0.5.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f17d5a03677efe6e2cbb67f20422bd1305b38fd87d80fd1131d8968e5df455e"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
