name = "GregTech Odyssey"
version = "0.5.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfd4e6482e95f18530d61acc6e651e98b72c31d6b10cbab1a9cee34fe15435a7"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
