name = "GregTech Odyssey"
version = "0.5.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0549e2530359a54b4ded16e86d55391fb2128f2d93614b92ab38ed0c22f99874"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
