name = "GregTech Odyssey"
version = "0.5.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03442493128b8b0e07fd8f0685c207d717be2abf424d3e3d019642095d04f680"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
