name = "GregTech Odyssey"
version = "0.5.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ca3342023535f272333253f3376499d5d9fad15a139f8ef7511916a797a9fcc"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
