name = "GregTech Odyssey"
version = "0.5.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1e54993fde893e42de52b18374b82c082cf34d69210034115d6f52b8d48303b"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
