name = "GregTech Odyssey"
version = "0.5.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dd90aadace9069a2b2f76316c7ebb949fe1ee3e869b8399e5af2ac82fa2ae55"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
