name = "GregTech Odyssey"
version = "0.5.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f79c12a1fc2d6bbdbefd2da58a9349e8fe9c6c0a2c2d22123aa33ee3538ec017"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
