name = "GregTech Odyssey"
version = "0.5.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "194e6e99e552ba60e7c5d744ab35a7fa9db39895ef72789577808d9cbf318183"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
