name = "GregTech Odyssey"
version = "0.5.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "221cbf17e937e6ece8bd4516ebd023b1bf946668c49286387cd1d32eab867286"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
