name = "GregTech Odyssey"
version = "0.5.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5907aa5ea947bf06db28fda056734f7e004128f40baba9732ae7471da7ef64c4"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
