name = "GregTech Odyssey"
version = "0.5.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae365fe5a11ce22149cc44719a586159c42a50917f6c373bd9d3fb943066f64e"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
