name = "GregTech Odyssey"
version = "0.5.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3189fbb7eaf1889ffc7bee21bfdfb05d04ede979dce0439a8905a10f18d0d70"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
