name = "GregTech Odyssey"
version = "0.5.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43219d872bd3f628ace2afd6523c3cb5f9c9f95a18ea44fabac93079654e1f55"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
