name = "GregTech Odyssey"
version = "0.5.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b08895e4329eac042d8cc8e18facf0a5f3794a2652b991d9cd55397c1d1f59ee"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
