name = "GregTech Odyssey"
version = "0.5.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02c2b8e2f952b5cddc12e3f7e3b0b2bf501c3c09b6c7603a8914d324291c268d"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
