name = "GregTech Odyssey"
version = "0.5.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45afdce4638907ff358a21e0161144f4f70221bf4356c62b94c4eda972b911d9"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
