name = "GregTech Odyssey"
version = "0.5.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9763f53ba495dc0750bbef89429f30cf710caa031c17d69772ff4095e1131891"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
